<?php

return [
    [
        'title' => 'HTML',
        'slug' => 'html',
        'icon' => 'fab fa-html5',
        'duration' => '2 Weeks',
        'fees' => 'PKR 5,000',
        'outline' => [
            'Introduction to HTML',
            'HTML Structure',
            'Text Formatting',
            'Links & Images',
            'Forms & Inputs',
            'Tables',
            'Semantic HTML',
            'SEO Best Practices',
        ],
    ],
    [
        'title' => 'CSS',
        'slug' => 'css',
        'icon' => 'fab fa-css',
        'duration' => '6 Weeks',
        'fees' => 'PKR 15,000',
        'outline' => [
            'CSS Syntax & Selectors',
            'Colors, Fonts, & Text Styling',
            'Box Model',
            'Flexbox',
            'Grid',
            'Positioning & Layouts',
            'Animations & Transitions',
            'Responsive Design & Media Queries',
            'CSS Best Practices',
        ],
    ],
    [
        'title' => 'JavaScript',
        'slug' => 'javascript',
        'icon' => 'fab fa-js',
        'duration' => '6 Weeks',
        'fees' => 'PKR 15,000',
        'outline' => [
            'Introduction to JavaScript',
            'Variables & Data Types',
            'Operators & Expressions',
            'Functions & Scope',
            'ES6 Features',
            'DOM Manipulation',
            'Events & Event Handling',
            'APIs & Fetch',
            'Async JS: Callbacks, Promises, Async/Await',
            'Debugging & Best Practices',
        ],
    ],
    [
        'title' => 'React.JS',
        'slug' => 'react-js',
        'icon' => 'fab fa-react',
        'duration' => '12 Weeks',
        'fees' => 'PKR 30,000',
        'outline' => [
            'Introduction to React',
            'JSX & Components',
            'Props & State',
            'Hooks (useState, useEffect)',
            'Event Handling',
            'Conditional Rendering',
            'Lists & Keys',
            'Forms & Controlled Components',
            'React Router',
            'Best Practices & Project Structure',
        ],
    ],
    [
        'title' => 'PHP/Laravel Development',
        'slug' => 'php-laravel',
        'icon' => 'fab fa-laravel',
        'duration' => '12 Weeks',
        'fees' => 'PKR 30,000',
        'outline' => [
            'Introduction to PHP',
            'PHP Syntax & Variables',
            'Arrays, Loops, & Functions',
            'Object-Oriented PHP',
            'Introduction to Laravel Framework',
            'MVC Architecture',
            'Routing & Controllers',
            'Blade Templates',
            'Database & Eloquent ORM',
            'Authentication & Authorization',
            'APIs with Laravel',
            'Deployment Best Practices',
        ],
    ],
    [
        'title' => 'Python Development',
        'slug' => 'python',
        'icon' => 'fab fa-python',
        'duration' => '12 Weeks',
        'fees' => 'PKR 30,000',
        'outline' => [
            'Introduction to Python',
            'Python Syntax & Variables',
            'Data Types & Operators',
            'Control Flow & Loops',
            'Functions & Modules',
            'Object-Oriented Programming',
            'File Handling',
            'Python Libraries & Packages',
            'Automation with Python',
            'Project: Practical Application',
        ],
    ],
    [
        'title' => 'Graphics Designing',
        'slug' => 'graphics-designing',
        'icon' => 'fas fa-paint-brush',
        'duration' => '12 Weeks',
        'fees' => 'PKR 30,000',
        'outline' => [
            'Introduction to Graphic Design',
            'Design Principles & Color Theory',
            'Typography',
            'Canva Basics & Templates',
            'Photoshop Tools & Techniques',
            'Illustrator Essentials',
            'Branding & Logo Design',
            'Design Projects & Portfolio',
        ],
    ],
    [
        'title' => 'Video Editing',
        'slug' => 'video-editing',
        'icon' => 'fas fa-video',
        'duration' => '12 Weeks',
        'fees' => 'PKR 30,000',
        'outline' => [
            'Introduction to Video Editing',
            'Premiere Pro Interface',
            'Importing & Organizing Footage',
            'Timeline Editing & Cutting',
            'Transitions & Effects',
            'Audio Editing & Mixing',
            'Color Correction & Grading',
            'Motion Graphics in After Effects',
            'Exporting & Deliverables',
        ],
    ],
];

